### ISSUE TITLE
Method not correctly added in the ClassDef when functions has name collision.

### ISSUE THREAD

**Issue by sboof911** [pyccel/pyccel#1507]
### Describe the bug
The error comes from: https://github.com/pyccel/pyccel/blob/2fb0e0da37382e0ed8c144865547a70bcbb14b8c/pyccel/parser/semantic.py#L3576-L3576
This line should change to : `m = self.scope.functions.pop(cls.scope.get_expected_name(m_name))`.
And check if the method is correctly added to the `ClassDef.methods`.

### To Reproduce
Provide code to reproduce the behavior:
```python
class Point:
     def __init__(self):
         self.x = 1
         self.X = 1

    def get_x(self):
        return self.x

    def get_X(self):
        return self.X
```

### Error details
Provide the generated code, or the error message:
```bash/fortran/c
File "/home/pyccel/pyccel/parser/semantic.py", line 1633, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/pyccel/pyccel/parser/semantic.py", line 3576, in _visit_ClassDef
    m = self.scope.functions.pop(m_name)
```

### Expected behavior
The Code should work and the methods should be correctly added to the `ClassDef.methods`.

**Comment by EmilyBourne** [comment]
This was not the error I was expecting to see. If the fix is just 1 line then maybe this should be included in your PR with the other scoping fixes

**Comment by sboof911** [comment]
> This was not the error I was expecting to see. If the fix is just 1 line then maybe this should be included in your PR with the other scoping fixes

Not just one I think it should change somethings besind that in syntactic or semantic.

**Comment by EmilyBourne** [comment]
I suspect that your suggested fix fixes:
```python
class Point:
     def __init__(self):
         pass

    def get_x(self):
        return 1

    def get_X(self):
        return 2
```

But not the provided example which was designed to highlight the syntactic problem

**Comment by sboof911** [comment]
This issue is resolved by the PR https://github.com/pyccel/pyccel/pull/1510.
I need to add tests for it in the issue https://github.com/pyccel/pyccel/issues/1444.

**Comment by EmilyBourne** [comment]
Will this issue be closed by #1576 ?

**Comment by EmilyBourne** [comment]
This issue is not fixed. There is no error raised, but the name conflict is not handled. The generated code is currently:

```fortran
module tmp22


  use, intrinsic :: ISO_C_Binding, only : b1 => C_BOOL , i64 => &
        C_INT64_T
  implicit none

  type, public :: Point
    integer(i64) :: x
    integer(i64) :: X_0001
    logical(b1) :: is_freed

    contains
    procedure :: create => Point_create
    procedure :: get_x => Point_get_x
    procedure :: free => Point_free
  end type Point

  contains


  !........................................

  subroutine Point_create(self)

    implicit none

    class(Point), intent(inout) :: self

    self%is_freed = .False._b1
    self%x = 1_i64
    self%X_0001 = 1_i64

  end subroutine Point_create

  !........................................


  !........................................

  function Point_get_x(self) result(Out_0001)

    implicit none

    integer(i64) :: Out_0001
    class(Point), intent(inout) :: self

    Out_0001 = self%x
    return

  end function Point_get_x

  !........................................

  !........................................


  !........................................

  subroutine Point_free(self)

    implicit none

    class(Point), intent(inout) :: self

    if (.not. self%is_freed) then
      ! pass
      self%is_freed = .True._b1
    end if

  end subroutine Point_free

  !........................................


end module tmp22
```

So the function `get_X` which should be renamed to `get_X_0001` (by the scope) is missing
