### ISSUE TITLE
(a+b)//2 translated to 0*(a+b)

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#163]
The following code
```
(a+b)//2
```
where a and b are ints is translated to
```
Int((1/2)*(a + b))
```
1 and 2 are ints so 1/2=0 not 0.5

**Comment by saidctb** [comment]
the bug is fixed the above is example is working now

**Comment by EmilyBourne** [comment]
This bug is not fixed. The following code still returns 0 instead of 1:

```
#$ header function test_intDiv(int,int)
def test_intDiv(a,b):
    return (a+b)//2


print(test_intDiv(0,2))
```

**Comment by EmilyBourne** [comment]
To fix, the following new line `second=second.n()` needs to be changed to `second=Float(second.n())`

**Comment by saidctb** [comment]
it's fixed it returns a 1 in your previous example, did you make a   pull  from the branch devel ?

**Comment by EmilyBourne** [comment]
Similarly 1/sqrt(2) is translated to (1/2)*sqrt(2.0d0) which is 0*sqrt(2)

**Comment by EmilyBourne** [comment]
The following code illustrates the bug:
```
from pyccel.decorators import types

@types('double')
def testing(x):
    from numpy import sqrt
    return 1.0/sqrt(2*x)

print(testing(1.0))
```

**Comment by saidctb** [comment]
the bug is fixed
