### ISSUE TITLE
Rename real->float in pyccel code (especially for output)

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#932]
**Describe the bug**
When a variable is defined inside an **if/else** the error is not clear

**To Reproduce**
Provide code to reproduce the behaviour:
```python
if condition:
  x = 0
else:
  x = 3.5
```

Provide the generated code, or the error message:
```shell
 |error [semantic]: test.py [4,8]| Incompatible types in assignment (|x| int <-> real)
```

**Expected behavior**
The message should make it obvious to the user how the error can be corrected. As `x` doesn't exist at the moment of the line with the error, it is not obvious why the assignment is incompatible

**Comment by EmilyBourne** [comment]
This has already been improved. It no longer raises the above error. But instead states:
```
Variable has already been defined with type 'int'. Type 'real' in assignment is incompatible (x=3.5)
```

@ratnania do you agree that it is fixed?

**Comment by yguclu** [comment]
I think that this is *almost* fixed. What remains to be clarified is a slight confusion that we have not resolved in Pyccel yet: a Python user that is not familiar with Fortran may not know what type "real" means, given that the Python type is called "float"...
